use_frameworks!

target 'SimpleFrameButton_Example' do
  pod 'SimpleFrameButton', :path => '../'

  target 'SimpleFrameButton_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
